---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/commit-id: 9e8f31774ea3795b11c5c444322e57394169ea2f
    app.quarkus.io/build-timestamp: 2024-01-08 - 03:00:47 +0000
  labels:
    app.kubernetes.io/name: journal-system-searching
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/managed-by: quarkus
  name: journal-system-searching
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app.kubernetes.io/name: journal-system-searching
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/commit-id: 9e8f31774ea3795b11c5c444322e57394169ea2f
    app.quarkus.io/build-timestamp: 2024-01-08 - 03:00:47 +0000
  labels:
    app.kubernetes.io/managed-by: quarkus
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.kubernetes.io/name: journal-system-searching
  name: journal-system-searching
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
      app.kubernetes.io/name: journal-system-searching
  template:
    metadata:
      annotations:
        app.quarkus.io/commit-id: 9e8f31774ea3795b11c5c444322e57394169ea2f
        app.quarkus.io/build-timestamp: 2024-01-08 - 03:00:47 +0000
      labels:
        app.kubernetes.io/managed-by: quarkus
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
        app.kubernetes.io/name: journal-system-searching
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: yaman/journal-system-searching:1.0.0-SNAPSHOT
          imagePullPolicy: Always
          name: journal-system-searching
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
